site_name: Problem Generator
theme:
  name: material

nav:
  - Home: index.md
  - Getting Started: 
      - Install: getting_started/install.md
      - tutorial: tutorials/getting_started.md
      
markdown_extensions:
  - markdown_katex


extra:
# Agregar mis contactos
  social:
  # Correo
    - icon: fontawesome/solid/square-envelope
      link: mailto:franciscosuarezbellon@gmail.com
      name: email
  #Github
    - icon: fontawesome/brands/github
      link: https://github.com/FVSB
      name: github
  # Linkedin
    - icon: fontawesome/brands/linkedin
      link: www.linkedin.com/in/francisco-vicente-su치rez-bell칩n-96110b257
      name: linkedin
 
    
# Agregar footer     
copyright: Copyright &copy; 2025 Francisco Vicente Su치rez Bell칩n